#!/bin/sh

MOD_PATH="/lib/modules/$(uname -r)/extra/"

case "$1" in
    start)
	    echo "Load misc-modules"
        
        # faulty
        insmod "$MOD_PATH"faulty.ko || exit 1
        major=$(awk "\$2==\"faulty\" {print \$1}" /proc/devices)
		
        if [ ! -z "$major" ]; then
            rm -f /dev/faulty
            mknod /dev/faulty c $major 0
        else
            echo "No device found in /proc/devices for driver faulty (this driver may not allocate a device)"
        fi
		
		# hello
		modprobe hello
		;;
	stop)
	    echo "Unload misc-modules"
		# invoke rmmod with all arguments we got
		rmmod faulty || exit 1
		rm -f /dev/faulty
		modprobe -r hello
		;;
	*)
	    echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0